/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author Jairo
 */

public class Login extends javax.swing.JFrame {
private boolean isPasswordVisible = false;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
         
 } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanLogin = new javax.swing.JPanel();
        lblganaderia = new javax.swing.JLabel();
        lblvaca = new javax.swing.JLabel();
        lblgranja = new javax.swing.JLabel();
        lblingresarcorreo = new javax.swing.JLabel();
        txtingresarcorreo = new javax.swing.JTextField();
        lblcontrasena = new javax.swing.JLabel();
        txtponercontrasena = new javax.swing.JPasswordField();
        btnbotonvista = new javax.swing.JButton();
        btnregistro = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btniniciarsecion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanLogin.setBackground(new java.awt.Color(112, 87, 72));
        PanLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblganaderia.setFont(new java.awt.Font("Lucida Bright", 1, 48)); // NOI18N
        lblganaderia.setForeground(new java.awt.Color(0, 0, 0));
        lblganaderia.setText("GANADERÍA RED POLL");
        PanLogin.add(lblganaderia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 580, 90));

        lblvaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vaca2.png"))); // NOI18N
        PanLogin.add(lblvaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 60, 60));

        lblgranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerdo (1).png"))); // NOI18N
        PanLogin.add(lblgranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 60, 70));

        lblingresarcorreo.setBackground(new java.awt.Color(102, 255, 102));
        lblingresarcorreo.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        lblingresarcorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblingresarcorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Correo (1).png"))); // NOI18N
        lblingresarcorreo.setText("Correo electrónico:");
        PanLogin.add(lblingresarcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, 50));

        txtingresarcorreo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtingresarcorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        txtingresarcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresarcorreoActionPerformed(evt);
            }
        });
        PanLogin.add(txtingresarcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 530, 60));

        lblcontrasena.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        lblcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblcontrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/persona1 (2).png"))); // NOI18N
        lblcontrasena.setText("Contraseña:");
        PanLogin.add(lblcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 260, 50));

        txtponercontrasena.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtponercontrasena.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        txtponercontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtponercontrasenaActionPerformed(evt);
            }
        });
        PanLogin.add(txtponercontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 527, 54));

        btnbotonvista.setBackground(new java.awt.Color(255, 255, 255));
        btnbotonvista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ojos2.png"))); // NOI18N
        btnbotonvista.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojos (1).png"))); // NOI18N
        btnbotonvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbotonvistaActionPerformed(evt);
            }
        });
        PanLogin.add(btnbotonvista, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, 54));

        btnregistro.setFont(new java.awt.Font("Lucida Bright", 0, 16)); // NOI18N
        btnregistro.setText("Registrarse");
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });
        PanLogin.add(btnregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, 145, 50));

        btnsalir.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        PanLogin.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 810, 111, 50));

        btniniciarsecion.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        btniniciarsecion.setText("Iniciar sesión");
        btniniciarsecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarsecionActionPerformed(evt);
            }
        });
        PanLogin.add(btniniciarsecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 170, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vaquitas.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        PanLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -110, 1130, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 883, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtponercontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtponercontrasenaActionPerformed

    }//GEN-LAST:event_txtponercontrasenaActionPerformed

    private void btnbotonvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbotonvistaActionPerformed
        if (isPasswordVisible) {
            txtponercontrasena.setEchoChar('*');
            isPasswordVisible = false;
        } else {
            txtponercontrasena.setEchoChar('\u0000');
            isPasswordVisible = true;
        }
    }//GEN-LAST:event_btnbotonvistaActionPerformed

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        Registro nuevo = new Registro();
        nuevo.setVisible(true);
        this.setVisible(false);   
    }//GEN-LAST:event_btnregistroActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btniniciarsecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarsecionActionPerformed
      
    }//GEN-LAST:event_btniniciarsecionActionPerformed

    private void txtingresarcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresarcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingresarcorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanLogin;
    private javax.swing.JButton btnbotonvista;
    private javax.swing.JButton btniniciarsecion;
    private javax.swing.JButton btnregistro;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcontrasena;
    private javax.swing.JLabel lblganaderia;
    private javax.swing.JLabel lblgranja;
    private javax.swing.JLabel lblingresarcorreo;
    private javax.swing.JLabel lblvaca;
    private javax.swing.JTextField txtingresarcorreo;
    private javax.swing.JPasswordField txtponercontrasena;
    // End of variables declaration//GEN-END:variables
}
