/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author Jairo
 */
import Login.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class Registro extends javax.swing.JFrame {
private boolean isPasswordVisible = false;
private List<Usuario> listaUsuarios = new ArrayList<>();
    private int rol_Id;
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        Botontranparente();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PanRegistro = new javax.swing.JPanel();
        lblvaca = new javax.swing.JLabel();
        lblgranja = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        pwdContra = new javax.swing.JPasswordField();
        btnAcceder = new javax.swing.JButton();
        cmbPersonas = new javax.swing.JComboBox<>();
        btnMostrar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanRegistro.setBackground(new java.awt.Color(153, 255, 204));
        PanRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblvaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vaca2.png"))); // NOI18N
        PanRegistro.add(lblvaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 60, 60));

        lblgranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerdo (1).png"))); // NOI18N
        PanRegistro.add(lblgranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 60, 70));

        btnregresar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        PanRegistro.add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 810, 159, 42));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro Ganaderia Red Poll");
        PanRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 510, 50));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setBorder(new javax.swing.border.MatteBorder(null));
        PanRegistro.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 450, 42));

        lblCorreo.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("Digite su correo electrónico:");
        PanRegistro.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 359, 41));

        lblContra.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        lblContra.setForeground(new java.awt.Color(0, 0, 0));
        lblContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContra.setText("Digite su contraseña:");
        PanRegistro.add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 260, 30));

        pwdContra.setBackground(new java.awt.Color(255, 255, 255));
        pwdContra.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        pwdContra.setForeground(new java.awt.Color(0, 0, 0));
        pwdContra.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pwdContra.setBorder(new javax.swing.border.MatteBorder(null));
        pwdContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContraActionPerformed(evt);
            }
        });
        PanRegistro.add(pwdContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 450, 40));

        btnAcceder.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnAcceder.setText("Acceder ");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        PanRegistro.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 198, 45));

        cmbPersonas.setBackground(new java.awt.Color(255, 255, 255));
        cmbPersonas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbPersonas.setForeground(new java.awt.Color(0, 0, 0));
        cmbPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veterinario", "Encargado de lechería" }));
        cmbPersonas.setBorder(null);
        cmbPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonasActionPerformed(evt);
            }
        });
        PanRegistro.add(cmbPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 200, -1));

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojos (1).png"))); // NOI18N
        btnMostrar.setBorder(null);
        btnMostrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ojos2.png"))); // NOI18N
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        PanRegistro.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 80, 60));

        lblNombre.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Digite su nombre y apellidos:");
        PanRegistro.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 360, 40));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(new javax.swing.border.MatteBorder(null));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        PanRegistro.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 450, 50));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Digite su rol:");
        PanRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 220, 40));

        btnsalir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        PanRegistro.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 810, 120, 40));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagendeplanta.jpg"))); // NOI18N
        lblfondo.setText("jLabel3");
        PanRegistro.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 1200, 870));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Botontranparente (){
    btnMostrar.setOpaque(false);
    btnMostrar.setContentAreaFilled(false);
    btnMostrar.setBorderPainted(false);   
    }
    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed

        Login registro = new Login();
        registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
      
        if (isPasswordVisible) {
            pwdContra.setEchoChar('*');
            isPasswordVisible = false;
        } else {
            pwdContra.setEchoChar('\u0000');
            isPasswordVisible = true;
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void pwdContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContraActionPerformed
     
    }//GEN-LAST:event_pwdContraActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
   //Aqui se obtienen los datos
    String nombre = txtNombre.getText();
    String correo = txtCorreo.getText();
    String contrasena = new String(pwdContra.getPassword()); 
    
    // Esto es para validar que en los campos en donde se escribe no esten vacios
    if (nombre.isEmpty()||correo.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa un correo y contraseña válidos.");
        return;
    }
    Usuario nuevoUsuario = new Usuario(nombre, correo, contrasena, rol_Id);
    
    // Agregar el nuevo usuario a la lista (simulado)
    listaUsuarios.add(nuevoUsuario);
    
    txtNombre.setText("");
    txtCorreo.setText("");
    pwdContra.setText("");
    
    JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.");
    Login ingresar = new Login();
   ingresar.setVisible(true);
   this.setVisible(false);
    }//GEN-LAST:event_btnAccederActionPerformed

    private void cmbPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonasActionPerformed
      // Obtener el rol seleccionado del JComboBox
    String rolSeleccionado = (String) cmbPersonas.getSelectedItem();
    
    // Asignar un ID numérico basado en el rol seleccionado
    int rolId;
    switch (rolSeleccionado) { 
        case "Administrador":
                rolId =Roles.Administrador;
                break;
        case "Veterinario":
            rolId = Roles.Veterinario;
            break;
        case "Encargado de Lechería":
            rolId = Roles.Encargado_lecheria;
            break;
        default:
            rolId = -1; // Valor por defecto o manejo de errores
            break;
    }  
    // Aquí puedes usar el rolId para registrar al usuario junto con el correo y contraseña ingresados
    // Asume que txtCorreo y txtContrasena son JTextField donde el usuario ingresa correo y contraseña
    
    String correo = txtCorreo.getText();
    String contrasena = new String(pwdContra.getPassword());
    
    // Validar que no estén vacíos
    if (correo.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa un correo y contraseña válidos.");
        return;
    }
    
    // Crear un nuevo usuario con el rol seleccionado
    Usuario nuevoUsuario = new Usuario(correo, contrasena, contrasena, rolId);
    
    // Agregar lógica para guardar el nuevo usuario en tu sistema (base de datos, lista, etc.)
    // Ejemplo: listaUsuarios.add(nuevoUsuario);
    listaUsuarios.add(nuevoUsuario);
    }//GEN-LAST:event_cmbPersonasActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanRegistro;
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblgranja;
    private javax.swing.JLabel lblvaca;
    private javax.swing.JPasswordField pwdContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
